"use client";
import { ReactNode } from "react";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.css";
import { Provider } from "react-redux";
import { store } from "../../store/store";
import { Poppins } from "next/font/google";
import localFont from "next/font/local";

interface RootLayoutProps {
  children: ReactNode;
}

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
// Initialize Poppins
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  display: "swap",
  style: ["normal", "italic"],
  variable: "--font-poppins", // For Tailwind or CSS
});
// Initialize SF UI Display with all weights
const sf = localFont({
  src: [
    {
      path: "../fonts/sf-ui-display/sf-ui-display-ultralight.woff",
      weight: "100",
      style: "normal",
    },
    {
      path: "../fonts/sf-ui-display/sf-ui-display-light.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "../fonts/sf-ui-display/sf-ui-display-thin.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/sf-ui-display/sf-ui-display-medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/sf-ui-display/sf-ui-display-semibold.woff",
      weight: "600",
      style: "normal",
    },
    {
      path: "../fonts/sf-ui-display/sf-ui-display-bold.woff", // ✅ Fixed path
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/sf-ui-display/sf-ui-display-heavy-586470160b9e5.woff",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-sf",
});

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap"
        />
        {/* <link rel="icon" href="./favicon.ico" /> */}
      </head>
      <body className={`${poppins.variable} ${sf.variable}`}>
        <Provider store={store}>{children}</Provider>
      </body>
    </html>
  );
}
